server:
  port: 8766
eureka:
  instance:
    hostname: server1
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8767/eureka/
  server:
    enable-self-preservation: false

spring:
  application:
    name: eureka-server

