server:
  port: 8767
eureka:
  instance:
    hostname: server2
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8766/eureka/
  server:
    enable-self-preservation: false

spring:
  application:
    name: eureka-server

